### ISSUE TITLE
`useMiniSearch` breaks Vite build

### ISSUE THREAD

**Issue by kculmback-eig** [lucaong/react-minisearch#32]
There seems to be an issue with the way that `useMiniSearch` is including MiniSearch in production builds.

Reproduction here:
https://stackblitz.com/edit/vitejs-vite-j8sehn

In that reproduction you'll see in the console there is the following error (after it is done building):
```
u.default.getDefault is not a function
```

Which is specifically referring to:
```
var idField = options.idField || MiniSearch__default["default"].getDefault('idField');
```

If I update the minisearch options to include `idField` and `extractField`, it works fine:

```typescript
import minisearch from 'minisearch'

const options: SearchOptions<SearchItem> = {
  fields: ['name', 'email'],
  storeFields: ['id'],
  searchOptions: {
    fuzzy: true,
    prefix: true,
  },

  // fixes build error
  idField: 'id',
  extractField: minisearch.getDefault('extractField'),
}
```

This is a fine stop gap solution, but it may be worth investigating why this is not working with Vite. I'm assuming it's due to Vite being an esm based bundler.

**Comment by lucaong** [comment]
Hi @kculmback-eig , thanks for reporting this. I am quite puzzled what the issue might be. The `getDefault` static method is [clearly defined in `MiniSearch`](https://github.com/lucaong/minisearch/blob/4eb53192cd3a2ad78b902554eb32c89c2c25b31f/src/MiniSearch.ts#L943), and other packagers like Webpack or rollup do not seem to have issues.

Could this be an issue with Vite? After all, the stop gap solution uses the same `getDefault` function, and does not error.

**Comment by lucaong** [comment]
This _might_ be a similar issue (but I know to little about Vite to tell): https://github.com/vitejs/vite/issues/9395
