### ISSUE TITLE
In development react re-renders at least twice (sometimes even more) so useMiniSearch hook throws an error for ID duplication

### ISSUE THREAD

**Issue by iamrakhmatov** [lucaong/react-minisearch#35]
const miniSearchOptions = { fields: ['title'] };

function Products() {
  const { search, searchResults } = useMiniSearch(data, miniSearchOptions);

  const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    search(event.target.value);
  };

<img width="921" alt="Screen Shot 2022-12-05 at 8 59 44 PM" src="https://user-images.githubusercontent.com/61634173/205683323-db05f261-9527-4d22-8c53-c6bd760a27c3.png">

It means I cannot use hook with React.StrickMode ?

**Comment by lucaong** [comment]
Hi @iamrakhmatov ,
thanks for reporting this! The issue should be fixed by https://github.com/lucaong/react-minisearch/pull/31 , which was just merged and released as `v6.0.2`.

**Comment by qin-guan** [comment]
Hey, it appears that there is a regression in the latest v6.0.3 release and this issue is occurring again

**Comment by lucaong** [comment]
Thanks @qin-guan , `v6.0.4` (just released on NPM) should fix it, could you confirm?
