### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by Immortalin** [lucaong/react-minisearch#4]
I have a large batch of documents to index (tens of megabytes), is there a way to await the indexing operation? (I am using the hook)

**Comment by lucaong** [comment]
Hi @Immortalin ,
yes, the documents are added asynchronously, and the `isIndexing` prop is `true` when the indexing is ongoing. So if you want, for example, to show a loading screen, you can rely on that prop.

If you prefer to await on a promise, you can index manually your documents by calling `addAllAsync`, which returns a promise that resolves when the indexing is done.
