### ISSUE TITLE
Exposing documentById map or reason not to?

### ISSUE THREAD

**Issue by mekodes** [lucaong/react-minisearch#49]
Hi @lucaong, hope this finds you well,

First of all, thank you for the great libs.

I noticed that react-minisearch is keeping an id to document map for the purposes of providing the search results as documents. However, this map isn't exposed. More specifically I was looking/hoping for a `getById` from the hook that would return the doc with the given id. I can of course fork this or keep track of the map myself but would rather avoid the duplication (and keeping things in sync for the available ops) if this is already handled and tracked somewhere.

Is there a reason something like this isn't exposed that I may be missing and if not, any interest in making this available? Would be more than happy to submit a PR.

All the best

**Comment by lucaong** [comment]
Hi @mekodes ,
there should be no reason against exposing a `getById` function. I am happy to accept PRs, or I would add such feature myself when I have some time.

Thanks for your input!

**Comment by mekodes** [comment]
Thank you @lucaong, really appreciate it, just submitted a PR.

All the best and happy holidays.
